[package]
name = "moliu-markdown-studio"
version = "0.1.0"
description = "墨流 Markdown 智能编辑器桌面端"
edition = "2021"
rust-version = "1.77.2"
build = "build.rs"

[lib]
name = "moliu_markdown_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
